# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: checkr/flagr-ci
    working_directory: /go/src/github.com/checkr/flagr
    steps:
      - checkout
      - run: make deps
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - run: cd browser/flagr-ui && yarn install && yarn run test

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Nestor hook
          command: >-
            curl -s
            "https://builder.internal.chpr.fr/api/builds/$CIRCLE_PROJECT_REPONAME?token=$NESTOR_TOKEN"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
